# Generated by Django 4.1.5 on 2023-01-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_user_current_country_user_native_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=255)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.existing_phrases')),
            ],
        ),
        migrations.DeleteModel(
            name='vistors',
        ),
        migrations.AddField(
            model_name='user',
            name='chosen_doaimn',
            field=models.CharField(choices=[('domain1', 'domain1'), ('domain2', 'domain2'), ('domain3', 'domain3'), ('domain4', 'domain4')], default='unknown', max_length=20),
        ),
    ]
