# Generated by Django 4.1.5 on 2023-01-17 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_phrasetable_delete_vistors_user_chosen_doaimn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chosen_doaimn',
        ),
        migrations.AddField(
            model_name='choise',
            name='ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.user'),
        ),
        migrations.AddField(
            model_name='choise',
            name='chosen_doaimn',
            field=models.CharField(choices=[('domain1', 'domain1'), ('domain2', 'domain2'), ('domain3', 'domain3'), ('domain4', 'domain4')], default='unknown', max_length=20),
        ),
    ]
